import { Product, Category, Testimonial, BlogPost, Review } from '@/types';

// ===== CATEGORIES =====
export const categories: Category[] = [
  {
    id: '1',
    name: 'Sâm Ngọc Linh',
    slug: 'sam-ngoc-linh',
    description: 'Sâm Ngọc Linh tươi và khô chính hãng từ Kon Tum',
    image: '/images/categories/sam-ngoc-linh.jpg',
    productCount: 12,
  },
  {
    id: '2',
    name: 'Thực Phẩm Chức Năng',
    slug: 'thuc-pham-chuc-nang',
    description: 'Viên nang, bột sâm và các sản phẩm chiết xuất',
    image: '/images/categories/tpcn.jpg',
    productCount: 8,
  },
  {
    id: '3',
    name: 'Rượu Sâm',
    slug: 'ruou-sam',
    description: 'Rượu sâm Ngọc Linh ngâm thượng hạng',
    image: '/images/categories/ruou-sam.jpg',
    productCount: 5,
  },
  {
    id: '4',
    name: 'Trà & Mật Ong',
    slug: 'tra-mat-ong',
    description: 'Trà sâm, mật ong rừng nguyên chất',
    image: '/images/categories/tra-mat-ong.jpg',
    productCount: 6,
  },
];

// ===== PRODUCTS =====
export const products: Product[] = [
  {
    id: '1',
    slug: 'sam-ngoc-linh-tuoi-tu-nhien-10-nam',
    name: 'Sâm Ngọc Linh Tươi Tự Nhiên 10 Năm Tuổi',
    shortDescription: 'Sâm Ngọc Linh tươi tự nhiên, thu hoạch từ rừng nguyên sinh Kon Tum, 10 năm tuổi. Hàm lượng saponin cao nhất thế giới.',
    description: `Sâm Ngọc Linh (Panax vietnamensis) là loại sâm quý hiếm bậc nhất, chỉ mọc trên đỉnh núi Ngọc Linh ở độ cao 1.500 - 2.500m. Với hơn 52 loại saponin (nhiều hơn cả Sâm Hàn Quốc), đây được mệnh danh là "Quốc bảo Việt Nam".

Sản phẩm Sâm Ngọc Linh Tươi 10 Năm Tuổi được thu hoạch trực tiếp từ vùng trồng chỉ dẫn địa lý tại Kon Tum, đảm bảo 100% tự nhiên, không thuốc trừ sâu, không hóa chất.`,
    price: 85000000,
    originalPrice: 95000000,
    images: [
      '/images/products/sam-tuoi-1.jpg',
      '/images/products/sam-tuoi-2.jpg',
      '/images/products/sam-tuoi-3.jpg',
    ],
    category: 'Sâm Ngọc Linh',
    categorySlug: 'sam-ngoc-linh',
    badges: ['bestseller', 'limited'],
    rating: 4.9,
    reviewCount: 127,
    inStock: true,
    stockQuantity: 15,
    variants: [
      { id: 'v1', name: '50g (1 củ)', price: 85000000, inStock: true },
      { id: 'v2', name: '100g (2-3 củ)', price: 160000000, inStock: true },
      { id: 'v3', name: '200g (4-5 củ)', price: 300000000, originalPrice: 320000000, inStock: false },
    ],
    benefits: [
      'Tăng cường hệ miễn dịch, chống oxy hóa mạnh mẽ',
      'Hỗ trợ phục hồi sức khỏe sau bệnh, sau phẫu thuật',
      'Cải thiện trí nhớ, tăng cường sự tập trung',
      'Điều hòa huyết áp, ổn định đường huyết',
      'Chống lão hóa, làm đẹp da từ bên trong',
      'Tăng sinh lực, giảm mệt mỏi, stress',
    ],
    ingredients: [
      { name: 'Saponin', amount: '12-15%', description: 'Hoạt chất chính, cao gấp 3 lần sâm Hàn Quốc' },
      { name: 'Ginsenoside Rg1', amount: '0.8%', description: 'Tăng cường trí nhớ, chống ung thư' },
      { name: 'Majonoside R2', amount: '5.3%', description: 'Đặc trưng chỉ có ở Sâm Ngọc Linh' },
      { name: 'Polysaccharides', amount: '8%', description: 'Tăng cường miễn dịch' },
    ],
    usage: 'Dùng 2-3 lát sâm tươi/ngày. Có thể ngậm trực tiếp, hãm trà hoặc nấu cháo. Nên sử dụng buổi sáng hoặc trước bữa ăn 30 phút.',
    warnings: [
      'Không dùng cho phụ nữ mang thai, trẻ em dưới 12 tuổi',
      'Người đang sử dụng thuốc chống đông máu cần tham khảo ý kiến bác sĩ',
      'Bảo quản ngăn mát tủ lạnh (2-8°C)',
    ],
    certifications: ['Chỉ dẫn địa lý Kon Tum', 'Kiểm định ATTP', 'GACP-WHO'],
    origin: 'Kon Tum, Việt Nam',
  },
  {
    id: '2',
    slug: 'vien-nang-sam-ngoc-linh-premium',
    name: 'Viên Nang Sâm Ngọc Linh Premium',
    shortDescription: 'Viên nang chiết xuất Sâm Ngọc Linh cô đặc, tiện lợi sử dụng hàng ngày. Hàm lượng saponin chuẩn hóa.',
    description: 'Viên nang Sâm Ngọc Linh Premium được sản xuất bằng công nghệ chiết xuất hiện đại, giữ nguyên hoạt chất quý từ củ sâm tươi.',
    price: 2500000,
    originalPrice: 3000000,
    images: ['/images/products/vien-nang-1.jpg'],
    category: 'Thực Phẩm Chức Năng',
    categorySlug: 'thuc-pham-chuc-nang',
    badges: ['bestseller', 'sale'],
    rating: 4.8,
    reviewCount: 89,
    inStock: true,
    stockQuantity: 50,
    variants: [
      { id: 'v1', name: 'Hộp 30 viên', price: 2500000, inStock: true },
      { id: 'v2', name: 'Hộp 60 viên', price: 4500000, originalPrice: 5000000, inStock: true },
    ],
    benefits: [
      'Tiện lợi sử dụng hàng ngày, dễ mang theo',
      'Hàm lượng saponin chuẩn hóa mỗi viên',
      'Tăng cường sức đề kháng, giảm mệt mỏi',
      'Hỗ trợ tuần hoàn máu, bảo vệ tim mạch',
    ],
    ingredients: [
      { name: 'Chiết xuất Sâm Ngọc Linh', amount: '500mg/viên', description: 'Chuẩn hóa 10% saponin' },
      { name: 'Vitamin E', amount: '15mg', description: 'Chống oxy hóa' },
    ],
    usage: 'Uống 2 viên/ngày sau bữa ăn sáng. Uống liên tục 3 tháng để đạt hiệu quả tối ưu.',
    warnings: ['Không dùng cho trẻ em dưới 12 tuổi', 'Bảo quản nơi khô ráo, thoáng mát'],
    certifications: ['ISO 22000', 'GMP', 'Kiểm định ATTP'],
    origin: 'Kon Tum, Việt Nam',
  },
  {
    id: '3',
    slug: 'ruou-sam-ngoc-linh-5-nam',
    name: 'Rượu Sâm Ngọc Linh 5 Năm Ngâm',
    shortDescription: 'Rượu sâm Ngọc Linh ngâm 5 năm, nồng độ hoạt chất cao, thích hợp làm quà biếu cao cấp.',
    description: 'Rượu Sâm Ngọc Linh được ngâm từ củ sâm nguyên chất trong rượu nếp cái hoa vàng, qua 5 năm ủ.',
    price: 15000000,
    originalPrice: 18000000,
    images: ['/images/products/ruou-sam-1.jpg'],
    category: 'Rượu Sâm',
    categorySlug: 'ruou-sam',
    badges: ['sale'],
    rating: 4.7,
    reviewCount: 45,
    inStock: true,
    stockQuantity: 20,
    benefits: [
      'Bổ thận tráng dương, tăng sinh lực',
      'Ổn định huyết áp, giảm mỡ máu',
      'Hỗ trợ tiêu hóa, kích thích ăn ngon',
      'Quà biếu sang trọng, ý nghĩa',
    ],
    ingredients: [
      { name: 'Sâm Ngọc Linh tươi', amount: '100g/lít', description: 'Sâm 5-7 năm tuổi' },
      { name: 'Rượu nếp cái hoa vàng', amount: '40°', description: 'Rượu truyền thống' },
    ],
    usage: 'Uống 1-2 ly nhỏ (20-30ml) mỗi ngày trước bữa ăn tối.',
    warnings: ['Không dùng cho người dưới 18 tuổi', 'Không lái xe sau khi sử dụng'],
    certifications: ['Kiểm định ATTP', 'Chứng nhận nguồn gốc'],
    origin: 'Kon Tum, Việt Nam',
  },
  {
    id: '4',
    slug: 'mat-ong-rung-nguyen-chat',
    name: 'Mật Ong Rừng Nguyên Chất Ngọc Linh',
    shortDescription: 'Mật ong rừng nguyên chất từ vùng núi Ngọc Linh, giàu enzyme và khoáng chất tự nhiên.',
    description: 'Mật ong rừng Ngọc Linh được thu hoạch từ tổ ong rừng tự nhiên trên dãy núi Ngọc Linh.',
    price: 850000,
    images: ['/images/products/mat-ong-1.jpg'],
    category: 'Trà & Mật Ong',
    categorySlug: 'tra-mat-ong',
    badges: ['new'],
    rating: 4.6,
    reviewCount: 32,
    inStock: true,
    stockQuantity: 35,
    benefits: [
      'Tăng cường hệ miễn dịch tự nhiên',
      'Chống viêm, kháng khuẩn hiệu quả',
      'Hỗ trợ tiêu hóa, làm đẹp da',
      'Bổ sung năng lượng tự nhiên',
    ],
    ingredients: [
      { name: 'Mật ong rừng', amount: '100%', description: 'Nguyên chất, không pha trộn' },
    ],
    usage: 'Pha 1-2 thìa với nước ấm (dưới 40°C) uống mỗi sáng. Có thể kết hợp với chanh.',
    warnings: ['Không dùng cho trẻ dưới 1 tuổi', 'Không hâm nóng trên 40°C'],
    certifications: ['Kiểm định ATTP'],
    origin: 'Kon Tum, Việt Nam',
  },
  {
    id: '5',
    slug: 'tra-sam-ngoc-linh-tui-loc',
    name: 'Trà Sâm Ngọc Linh Túi Lọc',
    shortDescription: 'Trà sâm Ngọc Linh tiện lợi dạng túi lọc, thích hợp cho người bận rộn muốn chăm sóc sức khỏe hàng ngày.',
    description: 'Trà sâm Ngọc Linh túi lọc được chế biến từ lá và thân sâm Ngọc Linh, giữ nguyên hương vị và dưỡng chất.',
    price: 450000,
    images: ['/images/products/tra-sam-1.jpg'],
    category: 'Trà & Mật Ong',
    categorySlug: 'tra-mat-ong',
    badges: ['new', 'bestseller'],
    rating: 4.5,
    reviewCount: 56,
    inStock: true,
    stockQuantity: 80,
    benefits: [
      'Giảm stress, thư giãn tinh thần',
      'Hỗ trợ giấc ngủ ngon',
      'Thanh lọc cơ thể, đẹp da',
      'Tiện lợi, dễ sử dụng',
    ],
    ingredients: [
      { name: 'Lá sâm Ngọc Linh', amount: '60%', description: 'Sấy khô tự nhiên' },
      { name: 'Thân sâm Ngọc Linh', amount: '30%', description: 'Cắt lát sấy khô' },
      { name: 'Cỏ ngọt', amount: '10%', description: 'Tạo vị ngọt tự nhiên' },
    ],
    usage: 'Hãm 1 túi với 200ml nước nóng 80-90°C, đợi 5-7 phút. Uống 2-3 lần/ngày.',
    warnings: ['Phụ nữ mang thai cần tham khảo ý kiến bác sĩ'],
    certifications: ['ISO 22000', 'Kiểm định ATTP'],
    origin: 'Kon Tum, Việt Nam',
  },
  {
    id: '6',
    slug: 'sam-ngoc-linh-kho-cat-lat',
    name: 'Sâm Ngọc Linh Khô Cắt Lát',
    shortDescription: 'Sâm Ngọc Linh khô cắt lát mỏng, tiện lợi cho việc hãm trà và nấu ăn hàng ngày.',
    description: 'Sâm Ngọc Linh khô được sấy bằng công nghệ sấy thăng hoa, giữ nguyên 95% hoạt chất.',
    price: 12000000,
    originalPrice: 14000000,
    images: ['/images/products/sam-kho-1.jpg'],
    category: 'Sâm Ngọc Linh',
    categorySlug: 'sam-ngoc-linh',
    badges: ['sale'],
    rating: 4.8,
    reviewCount: 73,
    inStock: true,
    stockQuantity: 25,
    variants: [
      { id: 'v1', name: '50g', price: 12000000, inStock: true },
      { id: 'v2', name: '100g', price: 22000000, originalPrice: 24000000, inStock: true },
    ],
    benefits: [
      'Bảo quản lâu dài, tiện lợi sử dụng',
      'Giữ nguyên hoạt chất nhờ công nghệ sấy thăng hoa',
      'Dễ dàng hãm trà, nấu cháo, hầm gà',
      'Tăng cường sức khỏe toàn diện',
    ],
    ingredients: [
      { name: 'Sâm Ngọc Linh khô', amount: '100%', description: 'Sấy thăng hoa' },
    ],
    usage: 'Hãm 3-5 lát với nước nóng, uống như trà. Hoặc hầm với gà, nấu cháo.',
    warnings: ['Bảo quản nơi khô ráo, thoáng mát, tránh ánh nắng trực tiếp'],
    certifications: ['Chỉ dẫn địa lý Kon Tum', 'GACP-WHO', 'Kiểm định ATTP'],
    origin: 'Kon Tum, Việt Nam',
  },
];

// ===== TESTIMONIALS =====
export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Nguyễn Văn Minh',
    avatar: '',
    role: 'Doanh nhân, 52 tuổi',
    content: 'Sau 3 tháng sử dụng sâm Ngọc Linh, tôi cảm nhận rõ rệt sự thay đổi. Giấc ngủ sâu hơn, tinh thần minh mẫn, làm việc không còn mệt mỏi như trước. Đặc biệt tin tưởng vì có đầy đủ giấy chứng nhận.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Trần Thị Hương',
    avatar: '',
    role: 'Bác sĩ, 45 tuổi',
    content: 'Tôi giới thiệu sâm Ngọc Linh cho nhiều bệnh nhân sau phẫu thuật. Kết quả phục hồi nhanh hơn rõ rệt. Sản phẩm ở đây luôn đảm bảo chất lượng, có kiểm định đầy đủ.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Lê Hoàng Phúc',
    avatar: '',
    role: 'Kỹ sư IT, 35 tuổi',
    content: 'Ban đầu tôi khá hoài nghi nhưng sau khi dùng viên nang sâm Ngọc Linh 2 tháng, sức đề kháng cải thiện rõ, không còn hay bị cảm vặt. Dịch vụ tư vấn rất tận tình.',
    rating: 4,
  },
  {
    id: '4',
    name: 'Phạm Thị Mai',
    avatar: '',
    role: 'Giáo viên, 58 tuổi',
    content: 'Mua trà sâm và mật ong làm quà tặng cho gia đình, ai cũng rất thích. Đóng gói đẹp, sang trọng, rất phù hợp làm quà biếu. Sẽ tiếp tục ủng hộ!',
    rating: 5,
  },
];

// ===== REVIEWS =====
export const sampleReviews: Review[] = [
  {
    id: '1',
    author: 'Nguyễn Thanh Tùng',
    avatar: '',
    rating: 5,
    date: '2026-04-15',
    content: 'Sâm tươi rất đẹp, củ to, nhiều rễ. Đóng gói cẩn thận, có tem chống giả đầy đủ. Ngậm vào cảm nhận được vị đắng nhẹ đặc trưng rồi ngọt hậu rất lâu. Rất hài lòng!',
    verified: true,
  },
  {
    id: '2',
    author: 'Trần Minh Đức',
    avatar: '',
    rating: 5,
    date: '2026-04-10',
    content: 'Lần thứ 3 mua ở đây, chất lượng luôn ổn định. Anh chủ tư vấn rất nhiệt tình, giải thích chi tiết cách dùng sao cho hiệu quả nhất.',
    verified: true,
  },
  {
    id: '3',
    author: 'Lê Thị Hoa',
    avatar: '',
    rating: 4,
    date: '2026-04-05',
    content: 'Mua viên nang cho ba mẹ uống. Sau 1 tháng ba mẹ nói ngủ ngon hơn, ăn ngon hơn. Giá hơi cao nhưng xứng đáng với chất lượng.',
    verified: true,
  },
];

// ===== BLOG POSTS =====
export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Cách Phân Biệt Sâm Ngọc Linh Thật - Giả',
    slug: 'cach-phan-biet-sam-ngoc-linh-that-gia',
    excerpt: 'Hướng dẫn chi tiết cách nhận biết sâm Ngọc Linh chính hãng, tránh mua phải hàng giả, hàng kém chất lượng.',
    content: '',
    image: '/images/blog/phan-biet-sam.jpg',
    author: 'Health Market',
    publishedAt: '2026-04-20',
    category: 'Kiến Thức',
    readTime: 8,
  },
  {
    id: '2',
    title: '10 Công Dụng Tuyệt Vời Của Sâm Ngọc Linh Được Khoa Học Chứng Minh',
    slug: '10-cong-dung-sam-ngoc-linh',
    excerpt: 'Tổng hợp 10 công dụng nổi bật của Sâm Ngọc Linh đã được các nghiên cứu khoa học quốc tế chứng minh.',
    content: '',
    image: '/images/blog/cong-dung-sam.jpg',
    author: 'Health Market',
    publishedAt: '2026-04-15',
    category: 'Sức Khỏe',
    readTime: 12,
  },
  {
    id: '3',
    title: 'Sâm Ngọc Linh: Từ Quốc Bảo Đến Bàn Ăn Gia Đình',
    slug: 'sam-ngoc-linh-quoc-bao-den-ban-an',
    excerpt: 'Khám phá hành trình từ rừng nguyên sinh Kon Tum đến các món ăn bổ dưỡng cho cả gia đình bạn.',
    content: '',
    image: '/images/blog/sam-gia-dinh.jpg',
    author: 'Health Market',
    publishedAt: '2026-04-10',
    category: 'Ẩm Thực',
    readTime: 6,
  },
];

// ===== HELPER =====
export function formatPrice(price: number): string {
  return new Intl.NumberFormat('vi-VN').format(price) + '₫';
}

export function getDiscountPercent(price: number, originalPrice: number): number {
  return Math.round(((originalPrice - price) / originalPrice) * 100);
}
